packages:
  - 'packages/*'

catalog:
  typescript: ~5.9.3
  tsdown: ^0.20.3
  unplugin-vue: ^7.1.1
  vite: 8.0.0-beta.13
  vue: ^3.5.27
  '@types/node': ^25.2.1
  '@vitejs/plugin-vue': ^6.0.4
  vue-tsc: ~3.2.4
